@echo off
echo Starting Chat System Servers...

echo Starting PeerJS Server on port 9000...
start "PeerJS Server" cmd /k "node peerjs-server.js"

echo Starting Main Backend Server on port 3000...
start "Backend Server" cmd /k "npm run dev"

echo Both servers are starting...
echo PeerJS Server: http://localhost:9000
echo Backend Server: http://localhost:3000
echo.
echo Press any key to exit...
pause > nul
